---
- name: restart postgresql
  systemd:
    name: postgresql
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: restart ufw
  systemd:
    name: ufw
    enabled: yes
    state: restarted
